name: DynamicShop
version: ${project.version}
main: me.sat7.dynamicshop.DynamicShop
depend: [Vault]
softdepend: [PlaceholderAPI, Jobs, PlayerPoints]
api-version: 1.16
authors: [sat7, jpenilla, Multitallented, Chris6ix, KevinDaGame, FlorianKoerner, Kapitowa, LincolnJota]
description: Full GUI shop with dynamic prices
commands:
  DynamicShop:
    description: "Full GUI shop with dynamic prices"
    aliases: [ds]
  shop:
    description: "Open shop menu"
  sell:
    description: "Sell items"
permissions:
  dshop.use:
    description: Allows use of the /ds command
    default: true
  dshop.sell:
    description: Allows use of the /sell command
    default: true
  dshop.use.qsell:
    description: Allows use of the /ds qsell command
    default: true